#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/SharedView.cshtml")]
    public partial class _Views_Shared_SharedView_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_SharedView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h1>This is a shared view</h1>");

        }
    }
}
#pragma warning restore 1591
